Vagrant.configure("2") do |config|
  config.vm.define "cm" do |web|
    web.vm.box = "centos/7"
    web.vm.hostname = 'cm'

    web.vm.network :private_network, ip: "192.168.49.101"
    web.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"

    web.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 8192]
      v.customize ["modifyvm", :id, "--name", "cm"]
    end
  end

  config.vm.define "cdsw" do |db|
    db.vm.box = "centos/7"
    db.vm.hostname = 'cdsw'

    db.vm.network :private_network, ip: "192.168.49.102"
    db.vm.network :forwarded_port, guest: 22, host: 10222, id: "ssh"

    db.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--name", "cdsw"]
    end
  end

  config.vm.define "cdep" do |db|
    db.vm.box = "centos/7"
    db.vm.hostname = 'cdep'

    db.vm.network :private_network, ip: "192.168.49.100"
    db.vm.network :forwarded_port, guest: 22, host: 10022, id: "ssh"

    db.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "cdep"]
    end
  end

end