# yum install -y ntp
# cat > ~root/.ssh/authorized_keys << EOF
# ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC5Zx7QmkQF+YIYxZ3z7KeD/CJAkzijm49QHQDIA0AnY2rLqFj09ZvKKFPVh+wnEU4PhKMVAGlBBjlItumxwx90BTstgnQqXK09GR4KBQAq2vpwUz4prkllj84wMrBlIAWcWXSJxO5zI4atcIDBnUw+W0dfgjMzgKAfnrg45xT+rMzQw41t1rtcURO3VgmvDHt1xAAZ/Zo5XjguOhIhdR9IOyTwyowHHcm2IGeuLuOeupAhcQc+7tEX+Jj8fxs9+0tbV4HYG3kM1Xe2r4kq5OPtM4YVOHRvqwmjmClR+i21iAs3EUWVRHI1KYywrULak7u01Y6PnI3pJ7pcO4HchgSR
# EOF
# chmod 600 ~root/.ssh/authorized_keys; chmod 600 ~systest/.ssh/authorized_keys
# useradd -u 12345 -g users -d /home/systest -s /bin/bash -p $(echo cloudera | openssl passwd -1 -stdin) systest

Vagrant.configure("2") do |config|
  config.vm.define "cm" do |web|
    web.vm.box = "centos/7"
    web.vm.hostname = 'cm'

    web.vm.network :private_network, ip: "192.168.49.101"
    web.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"

    web.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 8192]
      v.customize ["modifyvm", :id, "--name", "cm"]
    end
  end

  config.vm.define "cdsw" do |db|
    db.vm.box = "centos/7"
    db.vm.hostname = 'cdsw'

    db.vm.network :private_network, ip: "192.168.49.102"
    db.vm.network :forwarded_port, guest: 22, host: 10222, id: "ssh"

    db.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--name", "cdsw"]
      file_to_disk = "mydisk.vmdk"
      # unless File.exist?(file_to_disk)
      #   v.customize ["createmedium", "disk", "--filename", "mydisk.vmdk", "--format", "vmdk", "--size", 20 * 1024 ]
      # end
      # v.customize ["storageattach", "cdsw" , "--storagectl", "SATA Controller", "--port", "1", "--device", "0", "--type", "hdd", "--medium", "mydisk.vmdk"]
    end
  end

  config.vm.define "cdep" do |db|
    db.vm.box = "centos/7"
    db.vm.hostname = 'cdep'

    db.vm.network :private_network, ip: "192.168.49.100"
    db.vm.network :forwarded_port, guest: 22, host: 10022, id: "ssh"

    db.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "cdep"]
    end
  end

end
